name: E2E Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: maklarsystem
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: maklarsystem
        run: npx playwright install --with-deps
      - name: Create env
        working-directory: maklarsystem
        run: |
          cat > .env.local <<'ENV'
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_SITE_URL=http://localhost:3000
          ALLOW_TEST_ROUTES=true
          ENV
      - name: Build
        working-directory: maklarsystem
        run: npm run build
      - name: Start server
        working-directory: maklarsystem
        run: npm start &
      - name: Wait for server
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 > /dev/null; then
              echo "Server is up"; exit 0; fi; sleep 1; done; exit 1
      - name: Run Playwright
        working-directory: maklarsystem
        run: npx playwright test tests/e2e/login.spec.ts --reporter=line

